### PR TITLE
Cookie consent fix

### PR DESCRIPTION
**Pull request by evrardts**

### CODE REVIEW

**Comment by Gdewilde** [comment]
@evrardts great job, you still need to remove the Gatsby Google Analytics config.

**Comment by evrardts** [comment]
@Gdewilde done! Sorry always forget this config file.

**Comment by Gdewilde** [comment]
Don't forget package.json https://github.com/privacyradius/gdpr-checklist/blob/master/package.json

**Comment by evrardts** [comment]
@Gdewilde done

**Pull request merged**
